### ISSUE TITLE
Angle

### ISSUE THREAD

**Issue by wmcentire** [MatthewM5293/GAT150-2022#1]
Yo matt you misspelled angle as angel in your main you don't have to do anything about it just letting you know in case it comes up later

**Comment by MatthewM5293** [comment]
Fixed! Thanks for the heads up.
From: wmcentire ***@***.***>
Sent: Saturday, August 6, 2022 8:08 PM
To: MatthewM5293/GAT150-2022 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MatthewM5293/GAT150-2022] Angle (Issue #1)


[EXTERNAL EMAIL] DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

Yo matt you misspelled angle as angel in your main you don't have to do anything about it just letting you know in case it comes up later
